#### We do not use anymore. We pulled website development out of docker in PR #614

# adapted from https://github.com/microsoft/vscode-dev-containers/blob/main/containers/javascript-node-mongo/.devcontainer/docker-compose.yml
# Note: the "ports" property in this file will not forward from a codespace; add to "forwardPorts" in devcontainer.json instead
services:
  website:
    build:
      context: ..
      dockerfile: .devcontainer/website/website.Dockerfile
    volumes:
      - ../src/website:/website:cached
      - website-node-modules:/website/node_modules:delegated
      - website-tests-node-modules:/website/tests/node_modules:delegated

    # Runs on the same network as the workspace container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:sailbot-workspace

volumes:
  website-node-modules:
  website-tests-node-modules:
