# Configuration that enables the mandatory deployment modules and uses their defaults
can_transceiver_node:
  ros__parameters:
    enabled: true

local_transceiver_node:
  ros__parameters:
    enabled: true

mock_ais_node:
  ros__parameters:
    enabled: true

remote_transceiver_node:
  ros__parameters:
    enabled: true
